paths:
    migrations: %%PHINX_CONFIG_DIR%%/db/migrations
    seeds: %%PHINX_CONFIG_DIR%%/db/seeds

environments:
    default_migration_table: phinxlog
    default_database: production
    production:
        adapter: mysql
        host: localhost
        name: senshu
        user: root
        pass: 'pass'
        port: 3306
        charset: utf8

    development:
        adapter: mysql
        host: localhost
        name: senshu_dev
        user: root
        pass: 'pass'
        port: 3306
        charset: utf8

    testing:
        adapter: mysql
        host: localhost
        name: senshu_test
        user: root
        pass: 'pass'
        port: 3306
        charset: utf8
